// swift-tools-version: 5.9
import PackageDescription

// RunnerPoseKit — on-device 2D runner pose extraction.
//
// Consumed by the Flutter main app (via the `runner_pose` plugin) and by BenchApp.
// See docs/PLAN.md for the full design (規劃書 §03 / §04).
//
// Build & test: macOS + Xcode 15 (iOS 16 target). This package does NOT build on
// Linux — the Linux checkout only runs `scripts/` and holds `testdata/`.

let package = Package(
    name: "RunnerPoseKit",
    platforms: [
        .iOS(.v16),
        .macOS(.v13), // for unit tests / parity harness on the dev Mac
    ],
    products: [
        .library(name: "RunnerPoseKit", targets: ["RunnerPoseKit"]),
        .library(name: "RunnerAnalysisKit", targets: ["RunnerAnalysisKit"]),
    ],
    dependencies: [
        // Ultralytics YOLO Swift package — provides the YOLO26 Core ML detector wrapper.
        // Pinned < 9.0 per 規劃書 §02 (API break at 9.x).
        .package(
            url: "https://github.com/ultralytics/yolo-ios-app.git",
            "8.3.0" ..< "9.0.0"
        ),
    ],
    targets: [
        .target(
            name: "RunnerPoseKit",
            dependencies: [
                .product(
                    name: "UltralyticsYOLO",
                    package: "yolo-ios-app",
                    condition: .when(platforms: [.iOS])
                ),
            ],
            resources: [
                // Drop the .mlpackage files into Sources/RunnerPoseKit/Resources/ on the Mac.
                // They are .gitignore'd (large binaries) — see Resources/README.md.
                .process("Resources"),
            ]
        ),
        .target(
            name: "RunnerAnalysisKit",
            dependencies: []
        ),
        .testTarget(
            name: "RunnerPoseKitTests",
            dependencies: ["RunnerPoseKit"],
            resources: [
                // .copy keeps the Fixtures/ directory structure so the loader can
                // enumerate it. Files are generated by scripts/dump_parity_fixtures.py.
                .copy("Fixtures"),
            ]
        ),
        .testTarget(
            name: "RunnerAnalysisKitTests",
            dependencies: ["RunnerAnalysisKit"]
        ),
    ]
)
