// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse(
    {Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum RunnerAnalysisStageMessage {
  validating,
  prescan,
  tracking,
  pose2d,
  pose3d,
  speed,
  gait,
  export,
  sync,
  completed,
  failed,
}

enum RunnerAnalysisEventStatusMessage {
  started,
  progress,
  completed,
  skipped,
  failed,
}

class RunnerAnalysisVideoMessage {
  RunnerAnalysisVideoMessage({
    required this.cameraIndex,
    required this.path,
    required this.fps,
    required this.width,
    required this.height,
    required this.rotationDegrees,
  });

  int cameraIndex;

  String path;

  double fps;

  int width;

  int height;

  int rotationDegrees;

  Object encode() {
    return <Object?>[
      cameraIndex,
      path,
      fps,
      width,
      height,
      rotationDegrees,
    ];
  }

  static RunnerAnalysisVideoMessage decode(Object result) {
    result as List<Object?>;
    return RunnerAnalysisVideoMessage(
      cameraIndex: result[0]! as int,
      path: result[1]! as String,
      fps: result[2]! as double,
      width: result[3]! as int,
      height: result[4]! as int,
      rotationDegrees: result[5]! as int,
    );
  }
}

class RunnerAnalysisRequestMessage {
  RunnerAnalysisRequestMessage({
    required this.schemaVersion,
    required this.requestId,
    this.comparisonGroupId,
    required this.outputDirectoryPath,
    required this.videos,
  });

  String schemaVersion;

  String requestId;

  String? comparisonGroupId;

  String outputDirectoryPath;

  List<RunnerAnalysisVideoMessage?> videos;

  Object encode() {
    return <Object?>[
      schemaVersion,
      requestId,
      comparisonGroupId,
      outputDirectoryPath,
      videos,
    ];
  }

  static RunnerAnalysisRequestMessage decode(Object result) {
    result as List<Object?>;
    return RunnerAnalysisRequestMessage(
      schemaVersion: result[0]! as String,
      requestId: result[1]! as String,
      comparisonGroupId: result[2] as String?,
      outputDirectoryPath: result[3]! as String,
      videos:
          (result[4] as List<Object?>?)!.cast<RunnerAnalysisVideoMessage?>(),
    );
  }
}

class RunnerAnalysisFailureMessage {
  RunnerAnalysisFailureMessage({
    required this.code,
    required this.message,
    required this.retriable,
  });

  String code;

  String message;

  bool retriable;

  Object encode() {
    return <Object?>[
      code,
      message,
      retriable,
    ];
  }

  static RunnerAnalysisFailureMessage decode(Object result) {
    result as List<Object?>;
    return RunnerAnalysisFailureMessage(
      code: result[0]! as String,
      message: result[1]! as String,
      retriable: result[2]! as bool,
    );
  }
}

class RunnerAnalysisEventMessage {
  RunnerAnalysisEventMessage({
    required this.stage,
    required this.status,
    required this.sequence,
    this.progress,
    this.message,
    this.bundlePath,
    this.failure,
  });

  RunnerAnalysisStageMessage stage;

  RunnerAnalysisEventStatusMessage status;

  int sequence;

  double? progress;

  String? message;

  String? bundlePath;

  RunnerAnalysisFailureMessage? failure;

  Object encode() {
    return <Object?>[
      stage.index,
      status.index,
      sequence,
      progress,
      message,
      bundlePath,
      failure,
    ];
  }

  static RunnerAnalysisEventMessage decode(Object result) {
    result as List<Object?>;
    return RunnerAnalysisEventMessage(
      stage: RunnerAnalysisStageMessage.values[result[0]! as int],
      status: RunnerAnalysisEventStatusMessage.values[result[1]! as int],
      sequence: result[2]! as int,
      progress: result[3] as double?,
      message: result[4] as String?,
      bundlePath: result[5] as String?,
      failure: result[6] as RunnerAnalysisFailureMessage?,
    );
  }
}

class _RunnerAnalysisHostApiCodec extends StandardMessageCodec {
  const _RunnerAnalysisHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is RunnerAnalysisRequestMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is RunnerAnalysisVideoMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return RunnerAnalysisRequestMessage.decode(readValue(buffer)!);
      case 129:
        return RunnerAnalysisVideoMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class RunnerAnalysisHostApi {
  /// Constructor for [RunnerAnalysisHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RunnerAnalysisHostApi(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : __pigeon_binaryMessenger = binaryMessenger,
        __pigeon_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec =
      _RunnerAnalysisHostApiCodec();

  final String __pigeon_messageChannelSuffix;

  Future<void> startAnalysis(RunnerAnalysisRequestMessage request) async {
    final String __pigeon_channelName =
        'dev.flutter.pigeon.runner_pose.RunnerAnalysisHostApi.startAnalysis$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[request]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> cancelAnalysis() async {
    final String __pigeon_channelName =
        'dev.flutter.pigeon.runner_pose.RunnerAnalysisHostApi.cancelAnalysis$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> dispose() async {
    final String __pigeon_channelName =
        'dev.flutter.pigeon.runner_pose.RunnerAnalysisHostApi.dispose$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
}

class _RunnerAnalysisFlutterApiCodec extends StandardMessageCodec {
  const _RunnerAnalysisFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is RunnerAnalysisEventMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is RunnerAnalysisFailureMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return RunnerAnalysisEventMessage.decode(readValue(buffer)!);
      case 129:
        return RunnerAnalysisFailureMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class RunnerAnalysisFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec =
      _RunnerAnalysisFlutterApiCodec();

  void onEvent(RunnerAnalysisEventMessage event);

  static void setUp(
    RunnerAnalysisFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix =
        messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<
              Object?>(
          'dev.flutter.pigeon.runner_pose.RunnerAnalysisFlutterApi.onEvent$messageChannelSuffix',
          pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.runner_pose.RunnerAnalysisFlutterApi.onEvent was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final RunnerAnalysisEventMessage? arg_event =
              (args[0] as RunnerAnalysisEventMessage?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.runner_pose.RunnerAnalysisFlutterApi.onEvent was null, expected non-null RunnerAnalysisEventMessage.');
          try {
            api.onEvent(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
