// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FlutterError {
  return FlutterError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum RunnerAnalysisStageMessage: Int {
  case validating = 0
  case prescan = 1
  case tracking = 2
  case pose2d = 3
  case pose3d = 4
  case speed = 5
  case gait = 6
  case export = 7
  case sync = 8
  case completed = 9
  case failed = 10
}

enum RunnerAnalysisEventStatusMessage: Int {
  case started = 0
  case progress = 1
  case completed = 2
  case skipped = 3
  case failed = 4
}

/// Generated class from Pigeon that represents data sent in messages.
struct RunnerAnalysisVideoMessage {
  var cameraIndex: Int64
  var path: String
  var fps: Double
  var width: Int64
  var height: Int64
  var rotationDegrees: Int64

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> RunnerAnalysisVideoMessage? {
    let cameraIndex = __pigeon_list[0] is Int64 ? __pigeon_list[0] as! Int64 : Int64(__pigeon_list[0] as! Int32)
    let path = __pigeon_list[1] as! String
    let fps = __pigeon_list[2] as! Double
    let width = __pigeon_list[3] is Int64 ? __pigeon_list[3] as! Int64 : Int64(__pigeon_list[3] as! Int32)
    let height = __pigeon_list[4] is Int64 ? __pigeon_list[4] as! Int64 : Int64(__pigeon_list[4] as! Int32)
    let rotationDegrees = __pigeon_list[5] is Int64 ? __pigeon_list[5] as! Int64 : Int64(__pigeon_list[5] as! Int32)

    return RunnerAnalysisVideoMessage(
      cameraIndex: cameraIndex,
      path: path,
      fps: fps,
      width: width,
      height: height,
      rotationDegrees: rotationDegrees
    )
  }
  func toList() -> [Any?] {
    return [
      cameraIndex,
      path,
      fps,
      width,
      height,
      rotationDegrees,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RunnerAnalysisRequestMessage {
  var schemaVersion: String
  var requestId: String
  var comparisonGroupId: String? = nil
  var outputDirectoryPath: String
  var videos: [RunnerAnalysisVideoMessage?]

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> RunnerAnalysisRequestMessage? {
    let schemaVersion = __pigeon_list[0] as! String
    let requestId = __pigeon_list[1] as! String
    let comparisonGroupId: String? = nilOrValue(__pigeon_list[2])
    let outputDirectoryPath = __pigeon_list[3] as! String
    let videos = __pigeon_list[4] as! [RunnerAnalysisVideoMessage?]

    return RunnerAnalysisRequestMessage(
      schemaVersion: schemaVersion,
      requestId: requestId,
      comparisonGroupId: comparisonGroupId,
      outputDirectoryPath: outputDirectoryPath,
      videos: videos
    )
  }
  func toList() -> [Any?] {
    return [
      schemaVersion,
      requestId,
      comparisonGroupId,
      outputDirectoryPath,
      videos,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RunnerAnalysisFailureMessage {
  var code: String
  var message: String
  var retriable: Bool

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> RunnerAnalysisFailureMessage? {
    let code = __pigeon_list[0] as! String
    let message = __pigeon_list[1] as! String
    let retriable = __pigeon_list[2] as! Bool

    return RunnerAnalysisFailureMessage(
      code: code,
      message: message,
      retriable: retriable
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
      retriable,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RunnerAnalysisEventMessage {
  var stage: RunnerAnalysisStageMessage
  var status: RunnerAnalysisEventStatusMessage
  var sequence: Int64
  var progress: Double? = nil
  var message: String? = nil
  var bundlePath: String? = nil
  var failure: RunnerAnalysisFailureMessage? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> RunnerAnalysisEventMessage? {
    let stage = RunnerAnalysisStageMessage(rawValue: __pigeon_list[0] as! Int)!
    let status = RunnerAnalysisEventStatusMessage(rawValue: __pigeon_list[1] as! Int)!
    let sequence = __pigeon_list[2] is Int64 ? __pigeon_list[2] as! Int64 : Int64(__pigeon_list[2] as! Int32)
    let progress: Double? = nilOrValue(__pigeon_list[3])
    let message: String? = nilOrValue(__pigeon_list[4])
    let bundlePath: String? = nilOrValue(__pigeon_list[5])
    let failure: RunnerAnalysisFailureMessage? = nilOrValue(__pigeon_list[6])

    return RunnerAnalysisEventMessage(
      stage: stage,
      status: status,
      sequence: sequence,
      progress: progress,
      message: message,
      bundlePath: bundlePath,
      failure: failure
    )
  }
  func toList() -> [Any?] {
    return [
      stage.rawValue,
      status.rawValue,
      sequence,
      progress,
      message,
      bundlePath,
      failure,
    ]
  }
}

private class RunnerAnalysisHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return RunnerAnalysisRequestMessage.fromList(self.readValue() as! [Any?])
    case 129:
      return RunnerAnalysisVideoMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class RunnerAnalysisHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? RunnerAnalysisRequestMessage {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? RunnerAnalysisVideoMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class RunnerAnalysisHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return RunnerAnalysisHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return RunnerAnalysisHostApiCodecWriter(data: data)
  }
}

class RunnerAnalysisHostApiCodec: FlutterStandardMessageCodec {
  static let shared = RunnerAnalysisHostApiCodec(readerWriter: RunnerAnalysisHostApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RunnerAnalysisHostApi {
  func startAnalysis(request: RunnerAnalysisRequestMessage, completion: @escaping (Result<Void, Error>) -> Void)
  func cancelAnalysis(completion: @escaping (Result<Void, Error>) -> Void)
  func dispose(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class RunnerAnalysisHostApiSetup {
  /// The codec used by RunnerAnalysisHostApi.
  static var codec: FlutterStandardMessageCodec { RunnerAnalysisHostApiCodec.shared }
  /// Sets up an instance of `RunnerAnalysisHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: RunnerAnalysisHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startAnalysisChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runner_pose.RunnerAnalysisHostApi.startAnalysis\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAnalysisChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! RunnerAnalysisRequestMessage
        api.startAnalysis(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startAnalysisChannel.setMessageHandler(nil)
    }
    let cancelAnalysisChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runner_pose.RunnerAnalysisHostApi.cancelAnalysis\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelAnalysisChannel.setMessageHandler { _, reply in
        api.cancelAnalysis { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelAnalysisChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.runner_pose.RunnerAnalysisHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        api.dispose { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
private class RunnerAnalysisFlutterApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return RunnerAnalysisEventMessage.fromList(self.readValue() as! [Any?])
    case 129:
      return RunnerAnalysisFailureMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class RunnerAnalysisFlutterApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? RunnerAnalysisEventMessage {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? RunnerAnalysisFailureMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class RunnerAnalysisFlutterApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return RunnerAnalysisFlutterApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return RunnerAnalysisFlutterApiCodecWriter(data: data)
  }
}

class RunnerAnalysisFlutterApiCodec: FlutterStandardMessageCodec {
  static let shared = RunnerAnalysisFlutterApiCodec(readerWriter: RunnerAnalysisFlutterApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol RunnerAnalysisFlutterApiProtocol {
  func onEvent(event eventArg: RunnerAnalysisEventMessage, completion: @escaping (Result<Void, FlutterError>) -> Void)
}
class RunnerAnalysisFlutterApi: RunnerAnalysisFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FlutterStandardMessageCodec {
    return RunnerAnalysisFlutterApiCodec.shared
  }
  func onEvent(event eventArg: RunnerAnalysisEventMessage, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.runner_pose.RunnerAnalysisFlutterApi.onEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
