import 'dart:async';

/// Flutter-facing API for on-device runner pose (規劃書 §05 P5 / §11).
///
/// This is a skeleton. The real bridge is generated by Pigeon
/// (`pigeons/messages.dart` -> `ios/Classes/Messages.g.swift` +
/// `lib/messages.g.dart`) so the channel is typed. The Swift side calls
/// `RunnerPoseEngine.poses(for:)` and streams `RunnerPose` back as events.

class RunnerJoint {
  final int index; // 0..22, JointName order
  final double x; // original video pixels
  final double y;
  final double score;
  const RunnerJoint(this.index, this.x, this.y, this.score);
}

class RunnerPoseFrame {
  final int frameIndex;
  final double timeSeconds;
  final bool valid;
  final List<RunnerJoint> joints;
  const RunnerPoseFrame({
    required this.frameIndex,
    required this.timeSeconds,
    required this.valid,
    required this.joints,
  });
}

class RunnerPoseConfig {
  final String detectorModel; // 'yolo26n' | ...
  final int detectorCadence;
  final String computeUnits; // 'cpuAndNeuralEngine' | ...
  const RunnerPoseConfig({
    this.detectorModel = 'yolo26n',
    this.detectorCadence = 6,
    this.computeUnits = 'cpuAndNeuralEngine',
  });
}

abstract class RunnerPose {
  /// Stream per-frame poses for a local video file. Progress = frameIndex.
  /// The video never leaves the device (規劃書 §01).
  static Stream<RunnerPoseFrame> analyze(
    String videoPath, {
    RunnerPoseConfig config = const RunnerPoseConfig(),
  }) {
    // TODO(P5): call the Pigeon-generated host API; forward the event channel.
    throw UnimplementedError('wire Pigeon messages — see pigeons/messages.dart');
  }

  /// Encode the collected keypoints in the schema the backend `/analyze/keypoints`
  /// endpoint expects (規劃書 §11). Same layout as the current pipeline's 2D output.
  static Map<String, dynamic> toKeypointsPayload(
    List<RunnerPoseFrame> frames, {
    required double fps,
    required int frameWidth,
    required int frameHeight,
  }) {
    return {
      'fps': fps,
      'frame_size': [frameWidth, frameHeight],
      'frames': [
        for (final f in frames)
          {
            'frame': f.frameIndex,
            'valid': f.valid,
            'joints': [
              for (final j in f.joints) [j.x, j.y, j.score],
            ],
          }
      ],
    };
  }
}
